### ISSUE TITLE
Id relação OSM distritos

### ISSUE THREAD

**Issue by 0e1** [mapaslivres/localidades#12]
No Rio Grande do Sul, recentemente, foram mapeados pouco mais de 1200 distritos, que representam cerca de 11% dos distritos brasileiros. Estão listados em https://wiki.openstreetmap.org/wiki/Rio_Grande_do_Sul/Distritos.

Já preparei para adicionar o id das relações ao arquivo districts.csv. Mas antes de faze-lo, gostaria da opinião dos colaboradores sobre a conveniência de adicionar e distribuir dados parciais, já que nesse caso, cerca de 89% dos distritos não teriam o id da relação.

**Comment by vgeorge** [comment]
Tudo bem se faltam alguns ids. Seria legal também importar a população criando uma coluna "population". Tenho usado a convenção de usar títulos de colunas em inglês, mas para "sede" não tenho certeza de como traduzir. Talvez "townhall" ou "cityhall", aplicando um valor booleano, `yes/no`.

**Comment by 0e1** [comment]
E qual seria a melhor fonte para a população? O censo de 2010 ou as estimativas anuais do IBGE? 

Talvez não precise duma coluna para "sede". Essa informação está implícita no código do distrito. O código do distrito sede é formado pelo código da cidade com o sufixo 05.

Outra informação que me parece interessante é o gentílico, mas não encontrei uma fonte para eles.

**Comment by vgeorge** [comment]
O ideal seria ter a população mais recente. Até poderia ter algumas colunas com anos anteriores, mas não é essencial. Dá pra criar uma coluna para o gentílico, não estaria mal começar a criar uma base disso, já que não há outras fontes.

**Comment by 0e1** [comment]
Farei isso. Se não me engano, final de agosto o IBGE divulga estimativas populacionais. 

Mas antes estou comparando as tabelas atuais com os dados do IBGE2016.

No caso das cidades, a quantidade de municípios era a mesma, mas com algumas diferenças em grafias dos nomes.

Ainda não terminei, mas os dados de 2016 trazem mais distritos que a tabela atual.
