### ISSUE TITLE
Roraima

### ISSUE THREAD

**Issue by luis-fonseca** [mapaslivres/localidades#5]
Não foi encontrado nos arquivos de estados Roraima.

**Comment by luis-fonseca** [comment]
Atualizado o estado que falta e adicionado o timezone de alguns estados que faltam. Os dados do timezone foram baseados nesta informação, https://en.wikipedia.org/wiki/Time_in_Brazil

**Comment by vgeorge** [comment]
Subi as suas alterações. Valeu, Luis!  👍🏼
