### ISSUE TITLE
Outros websites na tabela de unidades federativas

### ISSUE THREAD

**Issue by 0e1** [mapaslivres/localidades#9]
É útil acrescentar outros websites à tabela de unidades federativas? Websites de assembleias legislativas, tribunal de justiça estadual, tribunal regional eleitoral, tribunal de contas estadual.

**Comment by vgeorge** [comment]
Não estou certo de que vale a pena estes dados estarem aqui, talvez faça sentido eles viverem em projetos específicos que façam uso.

**Comment by 0e1** [comment]
Eu também não estava certo. Comentei para saber outra opinião. Realmente, faz mais sentido estar em algo específico.
